logging:
  level: INFO
  path: ./logs

paths:
  splits: [ tuning, held_out ]
outcomes:
  synth_diag:
    type: [code]
    match: [
      ['S/DIAG']
      ]
    match_how: startswith
    case_sensitive: false
  synth_pos_diag:
    type: [code]
    match: [
      ['S/DIAG_POSITIVE']
      ]
    match_how: startswith
    case_sensitive: false
  synth_labs:
    type: [code]
    match: [
      ['S/LAB1']
      ]
    match_how: startswith
    case_sensitive: false