logging:
  level: INFO
  path: ./logs

exclude_held_out: false

features:
  values:
    value_creator_kwargs:
      num_bins: 25
      bin_mapping_func: 
        _target_: corebehrt.functional.features.values.power_bin_distance_mean
      add_prefix: false # option to add prefix to values based on concept
      # separator_regex: r"^([^/]+)/" # everything before the seperator is the prefix
  agg_kwargs:
    regex: ^(?:L/).* # example regex to aggregate all features that start with 'LAB'
    agg_func: 'first'
    
tokenizer:
  #sep_tokens: true
  cls_token: true

excluder:
  min_age: -1
  max_age: 120

