logging:
  level: INFO
  path: ./logs

model:
  cls: default

trainer_args:
  sampler_function: 
    _target_: corebehrt.modules.trainer.utils.Sampling.inverse_sqrt 
    # function to calculate sample weights. Possible options: inverse_sqrt and effective_n_samples
  loss_weight_function: 
    _target_: corebehrt.modules.trainer.utils.PositiveWeight.sqrt 
    # function to calculate positive weights. Possible options: sqrt and effective_n_samples
  batch_size: 200
  checkpoint_frequency: 1
  early_stopping: 10
  effective_batch_size: 400
  epochs: 50
  gradient_clip:
    clip_value: 1.0
  info: true
  shuffle: true
  stopping_criterion: roc_auc
  val_batch_size: 256
  use_autocast: true
  
optimizer:
  lr: 5e-4
  eps: 1e-6

scheduler:
  _target_: transformers.get_constant_schedule_with_warmup
  num_warmup_steps: 3
<<<<<<< HEAD
=======
  # num_training_steps: 1000000
>>>>>>> c00809f6 (added configs)

metrics:
  accuracy:
    _target_: corebehrt.modules.monitoring.metrics.Accuracy
    threshold: 0.6
  roc_auc:
    _target_: corebehrt.modules.monitoring.metrics.ROC_AUC
  pr_auc:
    _target_: corebehrt.modules.monitoring.metrics.PR_AUC
  percentage_positives:
    _target_: corebehrt.modules.monitoring.metrics.Percentage_Positives
  delong_roc_auc:
    _target_: corebehrt.modules.monitoring.metrics.Delong_ROC_AUC
  delong_roc_auc_std:
    _target_: corebehrt.modules.monitoring.metrics.Delong_ROC_AUC_std

  

 

