logging:
  level: INFO
  path: ./logs

paths:
  outcome: "synth_pos_diag.csv"
  
data:
  type: "finetune"
  truncation_len: 1024
  min_len: 0

outcome:
  n_hours_censoring: -48 #-2160 #-336 #-4320
  n_hours_start_follow_up: -1
  n_hours_end_follow_up: null 
