logging:
  level: INFO
  path: ./logs

paths:
  outcome: "synth_pos_diag.csv"
  exposure: "synth_diag.csv"
  initial_pids: "pids_tuning.pt"

selection:
  exclude_prior_outcomes: false 
<<<<<<< HEAD
  exposed_only: true 
=======
  exposed_only: false 
>>>>>>> c00809f6 (added configs)
  age:
    min_years: 0 
    max_years: 120 

index_date: 
  mode: relative 
  relative: 
    n_hours_from_exposure: 0

cv_folds: 1 
test_ratio: 0.1 
