logging:
  level: INFO
  path: ./outputs/logs

paths:
  data: ./tests/data/raw
  features: ./outputs/features
  outcomes: ./outputs//outcomes
  splits: [train, tuning, held_out]

outcomes:
  TEST_OUTCOME:
    type: [code]
    match: [['D0', 'D1']]
    exclude: ['D437']
    match_how: startswith
    case_sensitive: true

  TEST_CENSOR:
    type: [code]
    match: [['M112']]
    match_how: startswith
    case_sensitive: false

  TEST_COMBINED:
    combinations:
      primary:
        type: [code]
        match: [['M8']]
        match_how: startswith
      secondary:
        type: [code]
        match: [['LAB', 'D5']]
        match_how: startswith
      window_hours_min: -100
      window_hours_max: 100
      timestamp_source: primary
